export default {
  perfume_one: require('../assets/images/perfume_one.png'),
  fav: require('../assets/icon/fav.png'),
  cat: require('../assets/images/Cover.png'),
  catone: require('../assets/images/Cover_one.png'),
  cattwo: require('../assets/images/Cover_two.png'),
  cardwomen:require('../assets/images/cardwomen.png'),
  cardman:require('../assets/images/cardman.png'),
  perfum_two:require('../assets/images/perfume_two.png'),
  card:require('../assets/images/card.png'),
  banner:require('../assets/images/Banner.png'),
  sale_one:require('../assets/images/sale_one.png'),
  sale_two:require('../assets/images/sale_two.png'),
  share:require('../assets/icon/share.png'),
  wave:require('../assets/icon/wave.png'),
  spotii:require('../assets/images/spotii.png'),
  subscription:require('../assets/icon/subscription.png'),
  avtar:require('../assets/images/Avatar.png'),
  avtar_two:require('../assets/images/Avatar_two.png'),
  avtar_three:require('../assets/images/Avatar_three.png'),
  shine:require('../assets/icon/shine.png'),
  bus:require('../assets/icon/bus.png'),
  offer:require('../assets/icon/offer.png'),
  cashondelivery:require('../assets/icon/cashondelivery.png'),
  mins:require('../assets/icon/minus.png'),
  plus:require('../assets/icon/plus.png'),
  perfume:require('../assets/icon/perfume.png'),
  perfume_oil:require('../assets/icon/perfumeoil.png'),
  agarwood:require('../assets/icon/agarwood.png'),
  oud:require('../assets/icon/oud.png'),
  collection:require('../assets/icon/colletion.png'),
  gifts:require('../assets/icon/gifts.png'),
  sale:require('../assets/icon/sale.png'),
  about:require('../assets/icon/about.png'),
  ccontact:require('../assets/icon/contact.png'),
  ajmal_blu:require('../assets/images/ajmal_blu.png'),
  main_header:require('../assets/images/Main.png'),
  premium_one:require('../assets/images/premium_one.png'),
  premium_two:require('../assets/images/premium_two.png'),
  product_bg:require('../assets/images/product_bg.png'),
  addcontact:require('../assets/icon/addcontact.png'),
  viewall:require('../assets/images/viewall.png'),
  egift:require('../assets/images/egift.png'),
  short:require('../assets/icon/short.png'),
  shortase: require('../assets/icon/shortasc.png'),
  shortdes: require('../assets/icon/shortdesc.png'),
  filters:require('../assets/icon/filters.png'),
  button:require('../assets/icon/Button.png'),
  citrus:require('../assets/images/citrus.png'),
  fruity: require('../assets/images/fruity.png'),
  Checkboxselected: require('../../assets/selectedcheckbox.png'),
  Checkboxunselected: require('../../assets/checkbox.png')
};
